name: lore_of_the_ring
description: A Middle-earth-inspired quiz app using Flutter and Firebase.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase SDK
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8

  # Routing
  go_router: ^13.2.1

  # State Management
  provider: ^6.1.2

  # UI
  cupertino_icons: ^1.0.6

  # Animations / Tolkien theme
  lottie: ^2.7.0
  google_fonts: ^6.2.1

  # Date formatting
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
